name = "Relativistic Biliard"
description = "Relativistic billiards physics game"
port = 8081

[scripts]
install = "echo installed"
start = "python3 -m http.server ${PORT}"
update = ""
uninstall = ""

